Proj/Proj/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from myrecipe import urls

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Proj.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^logout/$', 'django.contrib.auth.views.logout', kwargs={'next_page': "/"}, name="logout"),
    url(r"", include('myrecipe.urls', namespace='myrecipe')),
    url(r'^admin/', include(admin.site.urls)),
    url('', include('django.contrib.auth.urls', namespace='auth')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r"", include("chef.urls", namespace = "chef")),
    
)

Proj/chef/urls.py
from django.conf.urls import patterns, include, url
import views

urlpatterns = patterns('',
    
    url(r"^chef/(?P<usrname>.*)/$", views.PublicChefView.as_view(), name = "chef"),
    url(r'^dashboard/$', views.DashboardView.as_view(), name = "dashboard"),
    url(r'^dashboard/recipes/$', views.ChefRecipesList.as_view(), name = "chefRecipes"),
    url(r'^dashboard/favorites/$', views.ChefFavoritesList.as_view(), name = "chefFavorites"),
    url(r'^dashboard/recipes/wholiked/$', views.WhoLiked.as_view(), name="wholiked"),
)

Proj/myrecipe/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView
from myrecipe import views

urlpatterns = patterns('',
                       
  ### Adds a new recipe. ###                     
  url(r'^add/$', views.NewRecipeView.as_view(template_name="myrecipe/addRecipe.html"), name="addRecipe"),
                       
  ### Ajax view for adding recipe. ###
  url(r'^new/$', views.RecipeAddView.as_view(), name="newRecipeData"),
                       
  ### Display list of all recipes. ###
  url(r'^all/$', views.RecipeList.as_view(), name="AllRecipes"),
                       
  ### Displays detailed view of a single recipe. ###
  url(r'^recipe/(?P<slug>[-\w\d]+)/$', views.SingleRecipe.as_view(), name="singleRecipe"),
                       
  ### Edit an existing recipe. ###
  url(r'^edit/(?P<slug>[-\w\d]+)/$', views.EditRecipe.as_view(), name="edit"),
                       
  ### Modify an existing recipe i.e. Edit or Delete ###
  url(r'^modify/$', views.Modify.as_view(), name="modify"),
                       
  ### Search for a recipe. ###
  url(r"^search/$", TemplateView.as_view(template_name = "myrecipe/searchForm.html"), name = "searchForm"),
                       
  ### Displays results of a search query. ###
  url(r'^search/results/$', views.SearchView.as_view(), name="search"),
                       
  ### Landing page for a search with no results. ### 
  url(r'^search/noresults/$', TemplateView.as_view(template_name = "myrecipe/noResults.html"), name="noResults"),
                       
  ### Deletes an existing recipe. ###
  url(r'^delete/(?P<slug>[-\w\d]+)/$', views.DeleteRecipe.as_view(), name="deleteRecipe"),
                       
  ### View to like a recipe. ###
  url(r'^like/$', views.ProcessLikes, name="like"),
                       
  ### Testing Python Social Auth ###
  url(r'^login/$', TemplateView.as_view(template_name = "myrecipe/login.html"), kwargs={'next_page': "dashboard"}, name="login"),
  
  ### Index page ###
  url(r'^/?$',  TemplateView.as_view(template_name = "myrecipe/index.html"), name="index"),
                                 
  ### BASE HTML PAGE ###
  url(r'^base?$',  TemplateView.as_view(template_name = "myrecipe/_base.html"), name="base"), 
                      
  ### 404 ###
  url(r'^error404/$',  TemplateView.as_view(template_name = "myrecipe/error404.html"), name="error404"), 
                       
  ### ABOUT ###
  url(r'^about/$',  TemplateView.as_view(template_name = "myrecipe/about.html"), name="about"), 
                       
   ### CONTACT ###
  url(r'^contact/$',  TemplateView.as_view(template_name = "myrecipe/contact.html"), name="contact"),
                       
)

Proj/chef/models.py
from django.db import models
from django.conf import settings
from jsonfield import JSONField

class UserProfile(models.Model):
  """
  The UserProfile model will hold secondary
  data associated with the User.
  """
  # The User that this object is connected to.
  user = models.OneToOneField(settings.AUTH_USER_MODEL, unique = True, blank = False)
  # Small biography of User.
  bio = models.TextField(max_length = 300, default = "", blank = True)
  favIngredients = JSONField(blank=True, default={"favIngredients":["", "", ""]})
  
  def __unicode__(self):
    return "%s Profile" %(self.user.username)


def createUserProfile(sender, **kwargs):
  """
  Create a UserProfile object each time a new User is created.
  """
  # If 'created' is True...
  if kwargs.get("created", None) and kwargs["created"]:
    # See if 'instance' exists...
    if kwargs.get("instance", None) and kwargs["instance"]:
      bioText = "Hey everyone! My name is " + kwargs["instance"].username + ", and I love to cook!"
      usrprofile, created = UserProfile.objects.get_or_create(user = kwargs["instance"], bio = bioText)

# Connect the signal.
models.signals.post_save.connect(createUserProfile, sender = settings.AUTH_USER_MODEL)

Proj/chef/views.py
import json
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseRedirect
from django.views.generic import View, DetailView, ListView
from django.core.urlresolvers import reverse
from django.views.generic.edit import ProcessFormView
from django.contrib.auth import get_user_model
from braces.views import LoginRequiredMixin
from myrecipe.models import Recipe

User = get_user_model()


class PublicChefView(DetailView):
  """
  View a Chef's public profile.
  """
  model = User
  template_name = "chef/chef.html"
  limit_by = 20
  
  def get_context_data(self, **kwargs):
    """
    Provide additional context data about the Chef (public User).
    """
    context = super(PublicChefView, self).get_context_data(**kwargs)
    usr = context["object"]
    context["recentRecipes"] = usr.recipe_set.all()[:self.limit_by]
    
    # if user has no favorite ingredients, var if false, else true
    hasFavIngred = False if usr.userprofile.favIngredients['favIngredients'].count('') == 3 else True
      
    context["hasFavIngred"] = hasFavIngred
      
    return context
  
  def get_object(self):
    if hasattr(self, 'object'):
      return self.object
    return get_object_or_404(User, username = self.kwargs.get("usrname", ""))
  
  def get(self, request, *args, **kwargs):
    self.object = self.get_object()
    
    if self.object == request.user:
      return HttpResponseRedirect(reverse('chef:dashboard'))
    else:
      return super(PublicChefView, self).get(request, *args, **kwargs)

  
########################################
# Function to see if user has any recipes with any likes
def UserHasLikes(user):
  if user and not user.is_anonymous():
    for r in user.recipe_set.all():
      if r.likes.exists():
        return True
  return False
########################################

class DashboardView(LoginRequiredMixin, DetailView, ProcessFormView):
  """
  Render a User's dashboard.
  """
  model = User
  template_name = "chef/dashboard.html"
  limit_by = 5
  
  def get_context_data(self, **kwargs):
    """
    Provide additional context data about the User.
    """
    context = super(DashboardView, self).get_context_data(**kwargs)
    context["recentRecipes"] = self.request.user.recipe_set.all()[:self.limit_by]
    context["recentLikes"] = self.request.user.favoriter.all()[:self.limit_by]
    if UserHasLikes(self.request.user):
      context["ifLikedByAny"] = True
    context["fav1"] = self.request.user.userprofile.favIngredients["favIngredients"][0]
    context["fav2"] = self.request.user.userprofile.favIngredients["favIngredients"][1]
    context["fav3"] = self.request.user.userprofile.favIngredients["favIngredients"][2]
    return context
  
  def get_object(self):
    return None
  
  
  def post(self, request, *args, **kwargs):
    msg=''
    if request.is_ajax():
      print "request was ajax"
      #import pdb; pdb.set_trace();
      request.user.userprofile.bio = request.POST.get('bio', None)
      print str(request.user.userprofile.bio)
      request.user.userprofile.favIngredients['favIngredients'][0] = request.POST.get('i1', None)
      request.user.userprofile.favIngredients['favIngredients'][1] = request.POST.get('i2', None)
      request.user.userprofile.favIngredients['favIngredients'][2] = request.POST.get('i3', None)
      request.user.userprofile.save()
      print str(request.user.userprofile.favIngredients)
      
      msg = 'Updated properly!!'
      print msg
      return HttpResponse(json.dumps({"msg":msg}), content_type="application/json")
    else:
      msg = 'Did not update properly'
      print msg
      return HttpResponseBadRequest(json.dumps({"msg":msg}), content_type="application/json")
  
class WhoLiked(LoginRequiredMixin, ListView):
  """
  Only an author can see who liked his/her recipe.
  """
  model = Recipe
  template_name= "chef/wholiked.html"
  paginate_by = 10
  page_kwarg = "page"
  
  def get_queryset(self):
    """
    Return list of each recipe with a sublist of users who liked them
    """
    print "I am " + str(self.request.user.username)
    return self.request.user.recipe_set.all()
  
  def get_context_data(self, **kwargs):
    """
    Return boolean variable 'ifLikedByAny' to 
    determine whether to tell the user or not
    """
    context = super(WhoLiked, self).get_context_data(**kwargs)
    if UserHasLikes(self.request.user):
      context["ifLikedByAny"] = True
    return context
  
  
class ChefRecipesList(LoginRequiredMixin, ListView):
  """
  Paginated list of User's created Recipes.
  """
  model = Recipe
  template_name = "chef/chefRecipes.html"
  paginate_by = 10
  page_kwarg = "page"
  
  def get_queryset(self):
    """
    Return the list of user's Recipes.
    """
    return self.request.user.recipe_set.all()
  
  def get_context_data(self, **kwargs):
    """
    Return boolean variable 'ifLikedByAny' to 
    determine whether to tell the user or not
    """
    context = super(ChefRecipesList, self).get_context_data(**kwargs)
    if UserHasLikes(self.request.user):
      context["ifLikedByAny"] = True
    return context


class ChefFavoritesList(LoginRequiredMixin, ListView):
  """
  Paginated list of User's favorited Recipes.
  """
  model = Recipe
  template_name = "chef/chefFavorites.html"
  paginate_by = 10
  page_kwarg = "page"
  
  def get_queryset(self):
    """
    Return the list of 'Favorited' Recipes.
    """
    return self.request.user.favoriter.all()
  
  def get_context_data(self, **kwargs):
    """
    Return boolean variable 'ifLikedByAny' to 
    determine whether to tell the user or not
    """
    context = super(ChefFavoritesList, self).get_context_data(**kwargs)
    if UserHasLikes(self.request.user):
      context["ifLikedByAny"] = True
    return context

Proj/chef/templates/chef/chefFavorites.html
{% extends 'myrecipe/_base.html' %}
{% load staticfiles %}

{% block title %}My Favorites{% endblock %}

{% block styles %}
{% endblock %}

{% block main %}

{% if user.is_authenticated %}
<div class="container">
   <div class="row">
     <div class="col-md-12">
        <ul class="nav nav-tabs">
          <li><a href="{% url 'chef:dashboard' %}">Dashboard</a></li>
          <li><a href="{% url 'chef:chefRecipes' %}">My Recipes</a></li>
          <li class="active"><a href="{% url 'chef:chefFavorites' %}">My Favorites</a></li>
          {% if ifLikedByAny %}
          <li><a href="{% url 'chef:wholiked' %}">Who Liked</a></li>
          {% endif %}
          <li class="exploreTab"><a href="{% url 'myrecipe:AllRecipes' %}">Explore</a></li>
        </ul>
     </div>
  </div>
</div>
{% endif %}




<div class="container"> <!-- CONTAINER -->
  
  <div class="well well-lg">
    <div class="row">

      {% for recipe in object_list %}
      <!-- START COLUMN -->
      <div class="col-xs-6 col-md-3">

        <!-- START THUMBNAIL -->
        <div class="thumbnail">

          <!-- START CAPTOPN -->
          <div class="caption greeting">
            <a href="{% url 'myrecipe:singleRecipe' recipe.slug %}"><h3>{{ recipe.shortenTitle }}</h3>
            <a href="{% url 'chef:chef' recipe.author %}"><p class="listViewAuthor">by {{recipe.author}}</p></a> 
            
            
            <p class="listView">
              <a href="{url 'myrecipe:singleRecipe' recipe.slug}">
                <span class="fa-stack fa-lg">
                  <i class="fa fa-square fa-stack-2x"></i>
                  <i class="fa fa-eye fa-stack-1x fa-inverse listViewIcon hoverstyle"></i>
                </span>
              </a>
              
              <a>
                <span class="fa-stack fa-lg">
                  <i class="fa fa-square fa-stack-2x"></i>
                  <i class="fa fa-thumbs-up fa-stack-1x fa-inverse listViewIcon hoverstyle"></i>
                </span>
              </a>
             </p>
            
            <!-- START ROW -->
            
                <span class="badge listView">
                  {{ recipe.pub_date|date:"SHORT_DATE_FORMAT" }}
                </span>
           
                <span class="badge listView">
                  <i class="fa fa-thumbs-up "></i>
                  {{ recipe.likes.count }}
                </span>
            
               <span class="badge listView">
                  <i class="fa fa-clock-o "></i>
                  {{ recipe.totalTime }} min.
                </span>
                
            
            <!-- END ROW -->
            
          </div>
          <!-- END CAPTOPN -->

          <!-- START FOOTER -->
          <div class="panel-footer">
            
            <i class="fa fa-tag listViewIcon"></i>
            
            {% for tag in recipe.threeTags %}
              <a href="{% url 'myrecipe:search' %}?recipeQuery={{ tag }}">{{ tag }}</a>,
            {% endfor %} 
            
          </div>
          <!-- END FOOTER -->

        </div>
        <!-- END THUMBNAIL -->

      </div>
      <!-- END COLUMN -->
      {% endfor %}

    </div>
    <!-- END ROW -->
    
  </div>
  <!-- END WELL -->
  
  <div class="row"> <!-- ROW -->
    <div class="col-md-12">
      {% if is_paginated %}
      {% if page_obj.has_previous %}
      <a href="{% url 'chef:chefRecipes' %}?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}
      <span>
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
      </span>
      {% if page_obj.has_next %}
      <a href="{% url 'chef:chefRecipes' %}?page={{ page_obj.next_page_number }}">Next</a>
      {% endif %}
      {% endif %}
    </div>
  </div><!-- END ROW -->
    
  <div class="row dashboardpage">
    <div class="col-md-12 text-center">
      {% if is_paginated %}

        {% if page_obj.has_previous %}
          <span class="badge page">
            <a href="{% url 'myrecipe:AllRecipes' %}?page={{ page_obj.previous_page_number }}">Previous</a>
          </span>
        {% endif %}

        <span class="page">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
          <span class="badge page">
            <a href="{% url 'myrecipe:AllRecipes' %}?page={{ page_obj.next_page_number }}">Next</a>
          </span>
        {% endif %}

      {% endif %}

    </div>
  </div>
  
</div> <!-- END OF CONTAINER -->


  
<!--
  <div class="container">
    <div class="row">
      <div class="col-md-12">
  <h1>Viewing your Favorited Recipes:</h1>
  <br>
  
  <div id="searchResults" class="pagination">
      {% for object in object_list %}
    <p><a href="{% url 'myrecipe:singleRecipe' object.slug %}">{{ object.title }}</a></p>
      {% endfor %}
  </div>
  
  <br>
 
  {% if is_paginated %}
    {% if page_obj.has_previous %}
      <a href="{% url 'chef:chefFavorites' %}?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}
    <span>
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
    </span>
    {% if page_obj.has_next %}
      <a href="{% url 'chef:chefFavorites' %}?page={{ page_obj.next_page_number }}">Next</a>
    {% endif %}
  {% endif %}
        </div>
    </div>
  </div>
-->
{% endblock %} 
  
{% block scripts %}
{% endblock %}

Proj/chef/templates/chef/chefRecipes.html
{% extends 'myrecipe/_base.html' %}
{% load staticfiles %}

{% block title %}My Recipes{% endblock %}

{% block styles %}
{% endblock %}


{% block main %}
<!-- <body id="home"> -->
  
 {% if user.is_authenticated %}
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <ul class="nav nav-tabs">
        <li><a href="{% url 'chef:dashboard' %}">Dashboard</a></li>
        <li class="active"><a href="{% url 'chef:chefRecipes' %}">My Recipes</a></li>
        <li><a href="{% url 'chef:chefFavorites' %}">My Favorites</a></li>
        {% if ifLikedByAny %}
        <li><a href="{% url 'chef:wholiked' %}">Who Liked</a></li>
        {% endif %}
        <li class="exploreTab"><a href="{% url 'myrecipe:AllRecipes' %}">Explore</a></li>
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <ul class="nav nav-pills subpills">
        <li class="active"><a href="#">All Recipes</a></li>
        <li><a href="{% url 'myrecipe:addRecipe' %}">Add Recipe</a></li>
        <li><a href="{% url 'myrecipe:modify' %}">Modify Recipe</a></li>
      </ul>
    </div>
  </div>
</div>
{% endif %}

<div class="container"> <!-- CONTAINER -->
  
  <div class="well well-lg">
    <div class="row">

      {% for recipe in object_list reversed %}
      <!-- START COLUMN -->
      <div class="col-xs-6 col-md-3">

        <!-- START THUMBNAIL -->
        <div class="thumbnail">

          <!-- START CAPTOPN -->
          <div class="caption greeting">
            <a href="{% url 'myrecipe:singleRecipe' recipe.slug %}"><h3>{{ recipe.shortenTitle }}</h3>
            <a href="{% url 'chef:chef' recipe.author %}"><p class="listViewAuthor">by {{recipe.author}}</p></a> 
            
            
            <p class="listView">
              <a href="{url 'myrecipe:singleRecipe' recipe.slug}">
                <span class="fa-stack fa-lg">
                  <i class="fa fa-square fa-stack-2x"></i>
                  <i class="fa fa-eye fa-stack-1x fa-inverse listViewIcon hoverstyle"></i>
                </span>
              </a>
              
              <a>
                <span class="fa-stack fa-lg">
                  <i class="fa fa-square fa-stack-2x"></i>
                  <i class="fa fa-thumbs-up fa-stack-1x fa-inverse listViewIcon hoverstyle"></i>
                </span>
              </a>
             </p>
            
            <!-- START ROW -->
            
                <span class="badge listView">
                  {{ recipe.pub_date|date:"SHORT_DATE_FORMAT" }}
                </span>
           
                <span class="badge listView">
                  <i class="fa fa-thumbs-up "></i>
                  {{ recipe.likes.count }}
                </span>
            
               <span class="badge listView">
                  <i class="fa fa-clock-o "></i>
                  {{ recipe.totalTime }} min.
                </span>
                
            
            <!-- END ROW -->
            
          </div>
          <!-- END CAPTOPN -->

          <!-- START FOOTER -->
          <div class="panel-footer">
            
            <i class="fa fa-tag listViewIcon"></i>
            
            {% for tag in recipe.threeTags %}
              <a href="{% url 'myrecipe:search' %}?recipeQuery={{ tag }}">{{ tag }}</a>,
            {% endfor %} 
            
          </div>
          <!-- END FOOTER -->

        </div>
        <!-- END THUMBNAIL -->

      </div>
      <!-- END COLUMN -->
      {% endfor %}

    </div>
    <!-- END ROW -->
    
  </div>
  <!-- END WELL -->
  
  <div class="row dashboardpage">
    <div class="col-md-12 text-center">
      {% if is_paginated %}

        {% if page_obj.has_previous %}
          <span class="badge page">
            <a href="{% url 'myrecipe:AllRecipes' %}?page={{ page_obj.previous_page_number }}">Previous</a>
          </span>
        {% endif %}

        <span class="page">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
          <span class="badge page">
            <a href="{% url 'myrecipe:AllRecipes' %}?page={{ page_obj.next_page_number }}">Next</a>
          </span>
        {% endif %}

      {% endif %}

    </div>
  </div>
  
</div> <!-- END OF CONTAINER -->



{% endblock %}
{% block scripts %}
{% endblock %}
    
  
  
<!-- </body> -->
  

Proj/chef/templates/chef/wholiked.html
{% extends 'myrecipe/_base.html' %}
{% load staticfiles %}

{% block title %}Who Liked{% endblock %}

{% block main %}

{% if user.is_authenticated %}
<div class="container">
   <div class="row">
     <div class="col-md-12">
    <ul class="nav nav-tabs">
      <li><a href="{% url 'chef:dashboard' %}">Dashboard</a></li>
      <li><a href="{% url 'chef:chefRecipes' %}">My Recipes</a></li>
      <li><a href="{% url 'chef:chefFavorites' %}">My Favorites</a></li>
      {% if ifLikedByAny %}
        <li class="active"><a href="{% url 'chef:wholiked' %}">Who Liked</a></li>
      {% endif %}
       <li class="exploreTab"><a href="{% url 'myrecipe:AllRecipes' %}">Explore</a></li>
    </ul>
     </div>
  </div>
</div>
{% endif %}



<div class="container"> <!-- CONTAINER -->
  <div class="well well-lg">  <!--WELL -->
    <div class="row"> <!-- ROW -->
      <div class="col-md-12">

        {% for recipe in object_list %}
        {% if recipe.likes.exists %}
        <div class="panel panel-default">
            <div class="panel-heading wholikedheading">

              <a href="{% url 'myrecipe:singleRecipe' recipe.slug %}">{{ recipe.title }}</a>

              <div class="pull-right">
                <span class="badge">
                  {{ recipe.pub_date|date:"SHORT_DATE_FORMAT" }}
                </span>

                <span class="badge">
                  <i class="fa fa-thumbs-up "></i>
                  {{ recipe.likes.count }}
                </span>
              </div>

            </div>
            <div class="panel-body">
              <h3>
                {% for u in recipe.likes.all %}
                  {% ifequal u user %}
                    <a href="{% url 'chef:chef' u.username %}"><span class="label liked label-default"><i class="fa fa-user"></i> me</span></a>
                  {% else %}
                    <a href="{% url 'chef:chef' u.username %}"><span class="label liked label-default"><i class="fa fa-user"></i> {{ u }}</span></a>
                  {% endifequal %}
                {% endfor %}
              </h3>
            </div>

        </div>
       {% endif %}
       {% endfor %}




      </div> <!-- END OF COLUMN -->
    </div> <!-- END OF ROW -->
  </div>  <!--END OF WELL -->
  
  
  <div class="row dashboardpage">
    <div class="col-md-12 text-center">
      {% if is_paginated %}

        {% if page_obj.has_previous %}
          <span class="badge page">
            <a href="{% url 'myrecipe:AllRecipes' %}?page={{ page_obj.previous_page_number }}">Previous</a>
          </span>
        {% endif %}

        <span class="page">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
          <span class="badge page">
            <a href="{% url 'myrecipe:AllRecipes' %}?page={{ page_obj.next_page_number }}">Next</a>
          </span>
        {% endif %}

      {% endif %}

    </div>
  </div>
</div> <!-- END OF CONTAINER -->
    
    
    
    

    



{% endblock %}

{% block scripts %}
{% endblock %}
  