Proj/Proj/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from myrecipe import urls

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Proj.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^logout/$', 'django.contrib.auth.views.logout', kwargs={'next_page': "/"}, name="logout"),
    url(r"", include('myrecipe.urls', namespace='myrecipe')),
    url(r'^admin/', include(admin.site.urls)),
    url('', include('django.contrib.auth.urls', namespace='auth')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r"", include("chef.urls", namespace = "chef")),
    
)

Proj/chef/urls.py
from django.conf.urls import patterns, include, url
import views

urlpatterns = patterns('',
    
    url(r"^chef/(?P<usrname>.*)/$", views.PublicChefView.as_view(), name = "chef"),
    url(r'^dashboard/$', views.DashboardView.as_view(), name = "dashboard"),
    url(r'^dashboard/recipes/$', views.ChefRecipesList.as_view(), name = "chefRecipes"),
    url(r'^dashboard/favorites/$', views.ChefFavoritesList.as_view(), name = "chefFavorites"),
    url(r'^dashboard/recipes/wholiked/$', views.WhoLiked.as_view(), name="wholiked"),
)

Proj/myrecipe/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView
from myrecipe import views

urlpatterns = patterns('',
                       
  ### Adds a new recipe. ###                     
  url(r'^add/$', views.NewRecipeView.as_view(template_name="myrecipe/addRecipe.html"), name="addRecipe"),
                       
  ### Ajax view for adding recipe. ###
  url(r'^new/$', views.RecipeAddView.as_view(), name="newRecipeData"),
                       
  ### Display list of all recipes. ###
  url(r'^all/$', views.RecipeList.as_view(), name="AllRecipes"),
                       
  ### Displays detailed view of a single recipe. ###
  url(r'^recipe/(?P<slug>[-\w\d]+)/$', views.SingleRecipe.as_view(), name="singleRecipe"),
                       
  ### Edit an existing recipe. ###
  url(r'^edit/(?P<slug>[-\w\d]+)/$', views.EditRecipe.as_view(), name="edit"),
                       
  ### Modify an existing recipe i.e. Edit or Delete ###
  url(r'^modify/$', views.Modify.as_view(), name="modify"),
                       
  ### Search for a recipe. ###
  url(r"^search/$", TemplateView.as_view(template_name = "myrecipe/searchForm.html"), name = "searchForm"),
                       
  ### Displays results of a search query. ###
  url(r'^search/results/$', views.SearchView.as_view(), name="search"),
                       
  ### Landing page for a search with no results. ### 
  url(r'^search/noresults/$', TemplateView.as_view(template_name = "myrecipe/noResults.html"), name="noResults"),
                       
  ### Deletes an existing recipe. ###
  url(r'^delete/(?P<slug>[-\w\d]+)/$', views.DeleteRecipe.as_view(), name="deleteRecipe"),
                       
  ### View to like a recipe. ###
  url(r'^like/$', views.ProcessLikes, name="like"),
                       
  ### Testing Python Social Auth ###
  url(r'^login/$', TemplateView.as_view(template_name = "myrecipe/login.html"), kwargs={'next_page': "dashboard"}, name="login"),
  
  ### Index page ###
  url(r'^/?$',  TemplateView.as_view(template_name = "myrecipe/index.html"), name="index"),
                                 
  ### BASE HTML PAGE ###
  url(r'^base?$',  TemplateView.as_view(template_name = "myrecipe/_base.html"), name="base"), 
                      
  ### 404 ###
  url(r'^error404/$',  TemplateView.as_view(template_name = "myrecipe/error404.html"), name="error404"), 
                       
  ### ABOUT ###
  url(r'^about/$',  TemplateView.as_view(template_name = "myrecipe/about.html"), name="about"), 
                       
   ### CONTACT ###
  url(r'^contact/$',  TemplateView.as_view(template_name = "myrecipe/contact.html"), name="contact"),
                       
)

Proj/myrecipe/models.py
from django.db import models
from django.contrib.auth.models import User
from jsonfield import JSONField
from taggit.managers import TaggableManager
from myrecipe.slug import unique_slugify

# Create your models here.
class Recipe(models.Model):
  title = models.CharField(blank=False, max_length=50)
  ingredients = JSONField(blank=False)
  ingredString = models.CharField(blank=False, default='', max_length=250)
  method = JSONField(blank=False)
  yieldAmt = models.PositiveIntegerField(blank=False)
  prepTime = models.PositiveIntegerField(blank=False)
  cookTime = models.PositiveIntegerField(blank=False)
  notes = models.TextField(blank=True)
  pub_date = models.DateTimeField(auto_now_add = True)
  author = models.ForeignKey(User)
  tags = TaggableManager(blank = True)
  slug = models.SlugField()
  #http://stackoverflow.com/questions/4658747/django-related-name-for-field-clashes
  likes = models.ManyToManyField(User, blank = True, related_name = "favoriter")
  

  def save(self, **kwargs):
    slug = '%s' % (self.title)
    unique_slugify(self, slug)
    self.ingredString = self.makeIngredToString()
    super(Recipe, self).save()
    
  def makeIngredToString(self):
    istring = ''
    for k in self.ingredients.keys():
      istring += self.ingredients[k] + ' '
    return istring
  
  @property
  def shortenTitle(self):
    if len(self.title) > 22:
      return self.title[:19] + '...'
    return self.title
  
  @property
  def threeTags(self):
    return self.tags.names()[:3]
    
  
  @property
  def totalTime(self):
    return self.prepTime + self.cookTime
  
  def __unicode__(self):
    return self.title
  

  
  

Proj/myrecipe/forms.py
import itertools
from django import forms
from myrecipe.models import Recipe
from django.utils.text import slugify

MAX_TAGS = 12

class RecipeForm(forms.ModelForm):
  title = forms.CharField(error_messages = {"required": "You must enter a title."})
  yieldAmt = forms.CharField(error_messages = {"required": "A recipe must have a Yield Amount."})
  cookTime = forms.CharField(error_messages = {"required": "A Recipe must have a Cook Time."})
  prepTime = forms.CharField(error_messages = {"required": "A recipe must have a Preparation time amount."})
  
  class Meta:
    model = Recipe
    exclude = ['author', 'pub_date', 'slug', 'ingredString', 'fav']

  ### clean function for ingredients ###
  def clean_ingredients(self):
    data = self.cleaned_data['ingredients']
    print self.cleaned_data
    
    # Check if all numbers are consecutive.
    #import pdb; pdb.set_trace();
    keys = sorted(data.keys())
    keys = [int(k) for k in keys]
    for k in keys:
      print k
    print "keys is: ", keys
    if not keys == range(1, max(keys) + 1):
      raise forms.ValidationError("Non-consecutive ingredients!")
    
    # Check if all dict values are strings.
    val = data.values()
    print "val is: ", val
    for v in val:
      if not isinstance(v, unicode):
        return forms.ValidationError(v, " is not an acceptable type of ingredient!")
    
    return data
  
  ### clean function for methods ###
  def clean_method(self):
    data = self.cleaned_data['method']
    print self.cleaned_data
    
    
    # Check if all numbers are consecutive.
    #import pdb; pdb.set_trace();
    keys = sorted(data.keys())
    keys = [int(k) for k in keys]
    if max(keys) < 2:
      raise forms.ValidationError("Must have at least 2 methods for recipe!")
    
    
    print "keys is: ", keys
    if not keys == range(1, max(keys) + 1):
      raise forms.ValidationError("Non-consecutive method steps!")
    
    # Check if all dict values are strings.
    val = data.values()
    print "val is: ", val
    for v in val:
      if not isinstance(v, unicode):
        return forms.ValidationError(v, " is not an acceptable method step!")
    
    return data
  
  ### clean function for tags ###
  def clean_tags(self):
    print "in tags clean function now!"
    data = self.cleaned_data.get("tags", None)
    
     # Do the number of tags exceed the maximum?
    if len(data) > MAX_TAGS:
      raise forms.ValidationError("Only allowed %s tags per Recipe." %(MAX_TAGS))
    
    # Turn all tags into lower case.
    data = [tag.lower() for tag in data]
    
    return data
    
  
  def save(self):
    print "In save function now!"
    recipe = super(RecipeForm, self).save(commit=False)
    
    if hasattr(self, "recipeAuthor"):
      recipe.author = self.recipeAuthor

    '''
    recipe.slug = orig = slugify(recipe.title)

    for x in itertools.count(1):
      if not Recipe.objects.filter(slug=recipe.slug).exists():
        break
        recipe.slug = '%s-%d' % (orig, x)
        
    print str(recipe.slug)
    '''
          
    recipe.save()
    return recipe
          

Proj/myrecipe/views.py
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseRedirect, Http404, HttpResponseForbidden
from django.views.generic import FormView, CreateView, ListView, DetailView, DeleteView, TemplateView
from django.utils.text import slugify
from braces.views import LoginRequiredMixin
from django.db.models import Q
from myrecipe.forms import RecipeForm
from myrecipe.models import Recipe
import json, itertools, operator
from chef.views import UserHasLikes

def gatherQuery(userSearch):
  '''
  
  Gathers query objects using user's search words
  '''
  userSearch = userSearch.replace(',', '')
  searchWordList = userSearch.split(' ')
  recipes = Recipe.objects.all()
  
  #import pdb; pdb.set_trace()
  
  q = Q(title__icontains=searchWordList[0]) | Q(ingredString__icontains=searchWordList[0]) | Q(tags__name__in=searchWordList)
  for word in searchWordList[1:]:
    q.add((Q(title__icontains=searchWordList[0]) | Q(ingredString__icontains=searchWordList[0]) | Q(tags__name__in=searchWordList)), q.connector)

  res = recipes.filter(q).distinct()
  return res

 
"""
userSearchSting = dfifjdlj''
recipeq = gatherQuery(userSearchString)
return Recipe.objects.filter(recipeq).distinct()
"""

def ProcessLikes(request):
  liked = False
  success = False
  msg = ''
  
  print "In ProcessLikes view!!!"
  #import pdb; pdb.set_trace()
  
  if request.is_ajax():
    if request.user.is_authenticated():
      user = request.user
      slug = request.POST.get('slug', None)
      print slug
      try:
        print "before getting recipe"
        recipe = Recipe.objects.get(slug=slug)
        print "after getting recipe..." + str(recipe.title) + " ,likes-" + str(recipe.likes.count())
        # If the user has already favorited this recipe, then unfavorite it
        
        #import pdb; pdb.set_trace();
          # Try to see if this User likes the recipe.
        if recipe.likes.filter(username = user.username).exists():
          print "user " + str(user) + " already likes " + str(recipe.title)
          recipe.likes.remove(user)
          print "user will now unlike it, likes:" + str(recipe.likes.count())
        else:
          recipe.likes.add(user)
          liked = True
          print "user liked it, likes:" + str(recipe.likes.count())
        success = True
        msg = "You liked this Recipe!"
      except: 
        msg = "Recipe does not exist"
    else:
      msg = "User not authenticated"
  else:
      msg = "Method not ajax"
        
  if success:
    return HttpResponse(json.dumps({"success":success, "liked":liked, "msg":msg}), content_type="application/json")
  else:
    return HttpResponseBadRequest(json.dumps({"success":success, "msg":msg}), content_type="application/json")
        
  
class SearchView(ListView):
  """
  Search Recipes by title, tags, and ingredients.
  Results are paginated.
  """
  model = Recipe
  template_name = "myrecipe/searchResults.html"
  context_object_name = "object_list"
  paginate_by = 10
  page_kwarg = "page"
  
  def get_context_data(self, **kwargs):
    context = super(SearchView, self).get_context_data(**kwargs)
    context['recipeQuery'] = self.request.GET.get('recipeQuery', None)
    return context
  
  def get(self, request, *args, **kwargs):
    """
    If no search results, then redirect to search form page.
    """
    self.object_list = self.get_queryset()
    if not self.object_list:
      return HttpResponseRedirect("%s?recipeQuery=%s" %(reverse("myrecipe:noResults"), self.userSearchString))
    
    return super(SearchView, self).get(request, *args, **kwargs)
  
  def get_queryset(self):
    """
    Return the list of Recipes.
    """
    #import pdb; pdb.set_trace();
    # If this function has already been called, simply return (exit) from it.
    if hasattr(self, "object_list"):
      return self.object_list
    
    self.userSearchString = self.request.GET.get("recipeQuery", None)
    
    if not self.userSearchString:
      return None
    recipeq = gatherQuery(self.userSearchString)
    
    return recipeq


class DeleteRecipe(DeleteView):
  '''
  Deletes a user's recipe based on slug-name
  '''
  model = Recipe
  template_name = "myrecipe/deleteRecipe.html"
  
  def get_success_url(self):
    return reverse('myrecipe:AllRecipes')
  
  def get_object(self):
    """
    Gets the Recipe to delete.
    If the Recipe does not belong to the (logged-in) User, then 
    raise a 403 error.
    """
    obj = super(DeleteRecipe, self).get_object()
    
    if not obj.author == self.request.user:
      raise Http404
    return obj


class RecipeIMList(object):
  '''
  Mixin to create different context variables for a recipe's ingredients and method fields.
  '''
  def get_context_data(self, **kwargs):
    print "Recipe MIXIN!!!"
    context = super(RecipeIMList, self).get_context_data(**kwargs)
    # making new context key
    context['ingredList'] = sorted(context['object'].ingredients.items())
    context['methodList'] = sorted(context['object'].method.items())
    print context['ingredList']
    return context


class RecipeAddView(LoginRequiredMixin, CreateView):
  form_class = RecipeForm
  model = Recipe
  # This is the 'editing' mode.
  edited = False
  
  def _allowed_methods(self):
    return ['post']
  
  def get_object(self):
    if self.edited:
      return get_object_or_404(self.model, slug = self.slug)
    return super(RecipeAddView, self).get_object()
  
  def post(self, request, *args, **kwargs):
    """
    Handles POST requests, instantiating a form instance with the passed
    POST variables and then checked for validity.
    """
    # If data was POSTed with the 'editing' flag, then override the existing model.
    if request.POST.get("edited", "") == str(True):
      self.edited = True
    
    form_class = self.get_form_class()
    
    if self.edited:
      self.slug = request.POST.get("slug", "")
      self.object = self.get_object()
      if not self.object.author == request.user:
        raise Http404
      form = form_class(request.POST, instance = self.object)
    else:
      form = self.get_form(form_class)
      form.recipeAuthor = request.user
    if form.is_valid():
        return self.form_valid(form)
    else:
        return self.form_invalid(form)
  
  def form_valid(self, form):
    # This method is called when valid form data has been POSTed.
    # It should return an HttpResponse.
    if self.request.is_ajax():
      form.save()
      form.save_m2m()
      redirect = reverse('chef:chefRecipes')
      return HttpResponse(json.dumps({'success':'was a success!', 'redirectUrl':redirect}), content_type='application/json')
    return super(RecipeAddView, self).form_valid(form)
  
  def form_invalid(self, form):
    if self.request.is_ajax():
      return HttpResponseBadRequest(json.dumps(form.errors), content_type='application/json')
    return super(RecipeAddView, self).form_invalid(form)

class RecipeList(ListView):
  model = Recipe
  template_name = "myrecipe/AllRecipes.html"
  queryset = Recipe.objects.order_by('-pub_date')
  paginate_by = 10
  page_kwarg = "page"
  
  def get_context_data(self, **kwargs):
    context = super(RecipeList, self).get_context_data(**kwargs)
    if UserHasLikes(self.request.user):
      context["ifLikedByAny"] = True
    return context

class Modify(ListView):
  """
  Paginated list of User's created Recipes.
  """
  model = Recipe
  template_name = "myrecipe/modifyRecipe.html"
  paginate_by = 10
  page_kwarg = "page"
  
  def get_queryset(self):
    """
    Return the list of user's Recipes.
    """
    return self.request.user.recipe_set.all()
  
  def get_context_data(self, **kwargs):
    context = super(Modify , self).get_context_data(**kwargs)
    if UserHasLikes(self.request.user):
      context["ifLikedByAny"] = True
    return context
  
  
class SingleRecipe(RecipeIMList, DetailView):
  model = Recipe
  template_name = "myrecipe/SingleRecipe.html"
  
  def get_context_data(self, **kwargs):
    context = super(SingleRecipe, self).get_context_data(**kwargs)
    context["request"] = self.request
    return context
  
class EditRecipe(RecipeIMList, DetailView):
  model = Recipe
  template_name = "myrecipe/EditRecipe.html"
  
  def get(self, request, *args, **kwargs):
    self.object = self.get_object()
    if not self.object.author == request.user:
      raise Http404
    return super(EditRecipe, self).get(request, *args, **kwargs) 
  
class NewRecipeView(LoginRequiredMixin, TemplateView):
  def get(self, request, *args, **kwargs):
    return super(NewRecipeView, self).get(request, *args, **kwargs)
  
  def get_context_data(self, **kwargs):
    context = super(NewRecipeView, self).get_context_data(**kwargs)
    if UserHasLikes(self.request.user):
      context["ifLikedByAny"] = True
    return context
  
  
 

Proj/myrecipe/templates/myrecipe/_base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %} | Soupbits</title>

    <!-- Bootstrap -->
    <link href="{% static 'myrecipe/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'myrecipe/css/bootstrap.icon-large.min.css' %}" rel="stylesheet">
    <link href="{% static 'myrecipe/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'myrecipe/css/style.css' %}" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400' rel='stylesheet' type='text/css'>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    
    {% block styles %}
    {% endblock %}
    <style>
      #alertBox, #successBox {
        display: none;
      }
    </style>
  </head>
  <body>
    
    
    <!-- NAV BAR -->
    <nav class="navbar navbar-default" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          
        </div>
        
        <div class="collapse navbar-collapse">
          
          <ul class="nav navbar-nav redHalf hovernav">
            <li><a href="{% url 'myrecipe:index' %}">Home</a></li>
            <li><a href="{% url 'myrecipe:about' %}">About</a></li>
            <li><a href="{% url 'myrecipe:contact' %}">Contact Us</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right yellowHalf">
            {% if user.is_authenticated %}
            <li><button id="base-logout-button" data-href="{% url 'logout' %}" type="button" class="btn btn-default navbar-btn"><strong>Logout</strong></button></li>
            {% else %}
            <li><a href="{% url 'myrecipe:login' %}"><button type="button" class="btn btn-default navbar-btn">Sign in</button></a></li>
            {% endif %}
          </ul>
       
        </div>
      </div>
    </nav>
    <!-- END OF NAV BAR -->
    
    {% if user.is_authenticated %}
    <nav class="navbar navbar-default secondnav text-center" role="navigation">
     <div class="container">
       
       <ul class="nav navbar-nav hovernav">
            <li><a href="{% url 'chef:dashboard' %}" id="chefname"><i class="fa fa-user"></i> Chef {{ user.username }}</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <form class="navbar-form" role="search" action="{% url 'myrecipe:search' %}" method="GET">
              <div class="input-group">
                <input type="text" class="form-control" style="font-family:PrintClearly;font-size:20px;" placeholder="search" name="recipeQuery">
                <div class="input-group-btn">
                  <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                </div>
              </div>
           </form>
          </ul>
      </div>
    </nav>
    {% endif %}
    
     <div class="container">
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div id="alertBox" class="alert alert-danger alert-dismissible fade in listView" role="alert">
            <button type="button" class="close" data-fdismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <div id="alertBoxInner"></div>
          </div>
        </div>
      </div>
    </div>
    
    <div class="container">
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div id="successBox" class="alert alert-info alert-dismissible fade in listView" role="alert">
            <button type="button" class="close" data-fdismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <div id="successBoxInner"></div>
          </div>
        </div>
      </div>
    </div>
 
    
    {% block main %}
    {% endblock %}
    
    <div class="footer">
    <div class="container text-center">
      
      <div class="row">
        <a href="{% url 'myrecipe:index' %}" class="btn btn-default starttodaybutton logofooter">Soupbits</a>
      </div>
      
      <div class="row"> 
        
        {% if user.is_authenticated %}
        <div class="col-md-4">
          <ul class="nav nav-pills nav-stacked list-unstyled">
            <li><a href="{% url 'chef:dashboard' %}">Chef {{ user.username }}</a></li>
            <li><a href="{% url 'chef:dashboard' %}">Dashboard</a></li>
            <li><a href="{% url 'chef:chefRecipes' %}">My Recipes</a></li>
            <li><a href="{% url 'chef:chefFavorites' %}">My Favorites</a></li>
          </ul>
        </div>
        
        

        <div class="col-md-4"> 
          <ul class="nav nav-pills nav-stacked list-unstyled">
            <li><a href="{% url 'myrecipe:AllRecipes' %}">Browse</a></li>
            <li><a href="#">Cooking tidbits</a></li>
          </ul>
        </div>
          

        <div class="col-md-4"> 
          <ul class="nav nav-pills nav-stacked list-unstyled">
            <li><a href="{% url 'myrecipe:index' %}">Home</a></li>
            <li><a href="{% url 'myrecipe:about' %}">About</a></li>
            <li><a href="{% url 'myrecipe:contact' %}">Contact</a></li>
          </ul>
        </div>
        
        
        {% else %}
        <div class="col-md-6"> 
          <ul class="nav nav-pills nav-stacked list-unstyled">
            <li><a href="{% url 'myrecipe:AllRecipes' %}">Browse</a></li>
            <li><a href="#">Cooking tidbits</a></li>
          </ul>
        </div>
          

        <div class="col-md-6"> 
          <ul class="nav nav-pills nav-stacked list-unstyled">
            <li><a href="{% url 'myrecipe:index' %}">Home</a></li>
            <li><a href="{% url 'myrecipe:about' %}">About</a></li>
            <li><a href="{% url 'myrecipe:contact' %}">Contact</a></li>
          </ul>
        </div>
        {% endif %}
        
      </div>
    </div>
    </div>
    
    
    <script type="text/javascript" src="{% static 'myrecipe/js/jquery.min.js' %}"></script>
    <script type="application/octet-stream" src="{% static 'myrecipe/js/jquery.min.map' %}"></script>
    <script type="text/javascript" src="{% static 'myrecipe/js/underscore-min.js' %}"></script>
    <script type="application/octet-stream" src="{% static 'myrecipe/js/underscore-min.map' %}"></script>
    
    <script type="text/javascript" src="{% static 'myrecipe/js/_base.js' %}"></script>
    <script type="text/javascript">
      $(document).ready(function() {
        $("#base-logout-button").click(function() {
          window.location = $(this).data("href");
        });
      });
    </script>
    
    {% block scripts %}
    {% endblock %}
    
  </body>
</html>

Proj/myrecipe/templates/myrecipe/contact.html
{% extends 'myrecipe/_base.html' %}
{% load staticfiles %}

{% block title %}No Results{% endblock %}

{% block styles %}
{% endblock %}

{% block main %}
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="jumbotron text-center">
        <h1 class="error404"><i class="fa fa-quote-left"></i> drop a line @sjbitcode <i class="fa fa-quote-right"></i></h1>
        <p><a class="btn btn-primary btn-lg starttodaybutton" href="{% url 'myrecipe:index' %}" role="button">Home</a></p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block scripts %}
{% endblock %}

Proj/myrecipe/templates/myrecipe/noResults.html
{% extends 'myrecipe/_base.html' %}
{% load staticfiles %}

{% block title %}No Results{% endblock %}

{% block styles %}
{% endblock %}

{% block main %}


{% if user.is_authenticated %}
<div class="container">
  <div class="row">
    <div class="col-md-12">
      
      <ul class="nav nav-tabs">
        <li><a href="{% url 'chef:dashboard' %}">Dashboard</a></li>
        <li><a href="{% url 'chef:chefRecipes' %}">My Recipes</a></li>
        <li><a href="{% url 'chef:chefFavorites' %}">My Favorites</a></li>
        {% if ifLikedByAny %}
        <li><a href="{% url 'chef:wholiked' %}">Who Liked</a></li>
        {% endif %}
        <li class="exploreTab active"><a href="{% url 'myrecipe:AllRecipes' %}">Explore</a></li>
      </ul>
      
    </div>
  </div>
</div>
{% endif %}


<div class="container">
  <div class="well well-lg">
    <div class="row">
      
      <div class="page-header text-center">
        {% if request.GET.recipeQuery %}
          <h1 class="addrecipetitle">No search results for <i class="fa fa-quote-left"></i>&nbsp;&nbsp;{{ request.GET.recipeQuery }}&nbsp;&nbsp;<i class="fa fa-quote-right"></i></h1>
        {% else %}
          <h1 class="addrecipetitle">No search results <i class="fa fa-quote-left"></i> ... <i class="fa fa-quote-right"></i></h1>
        {% endif %}
        
        <small>Try again!</small>
        <form class="navbar-form" role="search" action="{% url 'myrecipe:search' %}" method="GET">
            <div class="input-group">
              <input type="text" class="form-control" style="font-family:PrintClearly;font-size:20px;" placeholder="search" name="recipeQuery">
              <div class="input-group-btn">
                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
              </div>
            </div>
        </form>
      </div>
      
    </div>
  </div>
</div>
    
    
  
        
{% endblock %}


{% block scripts %}
{% endblock %}

Proj/myrecipe/templates/myrecipe/thanks.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Thank you</title>
	<link rel="stylesheet" href="css/style.css">
	<!--[if IE]>
		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
</head>

<body id="home">

  <center>
	<h1>THANKS, YO</h1>
  </center>

</body>
</html>